name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>replit</title>
  <link href="style.css" rel="stylesheet" type="text/css" />
</head>

<body>
  <div class='pInr'>
<div class='pEnt' id='postID-2589778403313602081'>
<div class='pS post-body postBody' id='postBody'>
<meta content='never' name='referrer'/>


  

<marquee bgcolor="blue" style="color: white; font-family: arial; font-size: 15px;">Refresh Jika eror dan Pilih CH lain | harap aktifkan rotasi layar anda untuk mode full screen! </marquee>  
    
       


<script src='//cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js'></script>
<script>
document.addEventListener('DOMContentLoaded', () => {
  const players = document.querySelectorAll('.player')
  let playingInstance = null
  players.forEach(player => {
    const clapprConfig = {
      source: player.getAttribute("src"),
      poster: player.getAttribute("poster"),
      autoPlay: player.getAttribute("auto"),
      height: "300",
      position: 'center',
      width: "100%",
      plugins: [DashShakaPlayback, LevelSelector],
       levelSelectorConfig: {
    title: 'Quality',
    labels: {
        3: 'HD',// 700kbps
        2: 'High', // 500kbps
        1: 'Med', // 240kbps
        0: 'Low', // 120kbps
    },
    labelCallback: function(playbackLevel, customLabel) {
        return customLabel + playbackLevel.level.height+'p'; // High 720p
    }
  },

      
       watermark: 'https://i.postimg.cc/MH84vwy2/logolsbtv.png',
            position: 'bottom-right',
      shakaConfiguration: {
          drm: {
                clearKeys: {
                    'cfb5e2b73bef4f3c878f25ab86a7451f': '0d6712bf2a84edcc93d001a9613f6fec'
                    }
                }
            },
            shakaOnBeforeLoad: function(shaka_player) {
                // shaka_player.getNetworkingEngine().registerRequestFilter() ...
            },
      
    }
    const clappr = new Clappr.Player(clapprConfig);
    clappr.attachTo(player)
    clappr.on(Clappr.Events.PLAYER_PLAY, function() {
 
		})
    
    var mediaOnPage = Array.prototype.slice.apply(document.querySelectorAll('audio, video'))
mediaOnPage.forEach(function(mediumOnPage)
  {
    mediumOnPage.addEventListener('play', function(event)
      {
        mediaOnPage.forEach(function(mediumOnPage)
          {
            if (event.target != mediumOnPage)
              {
                mediumOnPage.pause();
              }
          })
      })
  })
  });
});
</script>

    <script src="https://cdn.jsdelivr.net/gh/clappr/clappr@latest/dist/clappr.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/clappr/dash-shaka-playback@latest/dist/dash-shaka-playback.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/level-selector@0.2.0/dist/level-selector.min.js" type="text/javascript"></script>
     <script src='https://cdn.jsdelivr.net/gh/NaughtyJoker29/live/tv.js' type='text/javascript'></script>




      
    
  
   <section id="content3">
   
    <div class="player" src="https://dce-fs-live-dazn-cdn.dazn.com/dashdrm/dazn-linear-017/stream.mpd" poster=""></div>


  </section>
  

    
</main>  

  <script src="script.js"></script>

 <!--
  This script places a badge on your repl's full-browser view back to your repl's cover
  page. Try various colors for the theme: dark, light, red, orange, yellow, lime, green,
  teal, blue, blurple, magenta, pink!
  -->
</script>
<div id='fixedban' style='width:100%;margin:auto;text-align:center;float:none;overflow:hidden;display:scroll;position:fixed;bottom:10;z-index:999;-webkit-transform:translateZ(0);'>
<div>
<a id='close-fixedban' onclick='document.getElementById("fixedban").style.display = "none";' style='cursor:pointer;'><img alt='close' src='https://1.bp.blogspot.com/-_A83iDM6JYc/VhtxROLILrI/AAAAAAAADK4/aM4ikIA6aqI/s1600/btn_close.gif' title='close button' style='vertical-align:middle;'/></a></div>
<div style='text-align:center;display:block;max-width:80%;height:auto;overflow:hidden;margin:auto'>

<a href="https://t.me/tvlivestreamingbola"><div style="background: #00b7ff; padding: 5px; color: white; font-size: 0.8em;">>> Join Telegram Live streaming tv <<<br>Dapatkan Link Streaming lainnya<<<br>Aktifkan rotasi hp anda untuk full screen</div></a></script> 
</body>
<body bgcolor=â€#800000">
</html>
